
[build-system]
requires = [
    "setuptools>=61.2",
    "Cython>=0.29.22,<3.0",
    "oldest-supported-numpy",
]

[project]
name = "ewah_bool_utils"
version = "0.1.1"
description = "EWAH Bool Array utils for yt"
authors = [
  { name = "Matthew Turk" },
  { name = "Meagan Lang"},
  { name = "Navaneeth Suresh"},
]
requires-python =">=3.8"
dependencies = [
  "numpy>=1.17.5",
]

[project.license]
text = "BSD"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"


[project.urls]
Homepage = "https://github.com/yt-project/ewah_bool_utils"

[tool.setuptools]
license-files = [
    "LICENSE",
]