name: Build wheels and publish to PyPI

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    paths:
    - .github/workflows/wheels.yaml
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - windows-2019
        - macos-13    # x86_64
        - macos-14    # arm64

      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build wheels for CPython
      uses: pypa/cibuildwheel@v2.18.1
      with:
        output-dir: dist
      env:
        CIBW_BUILD: cp39-* cp310-* cp311-* cp312-*
        CIBW_ARCHS_LINUX: x86_64
        MACOSX_DEPLOYMENT_TARGET: '10.9'   # as of CIBW 2.9, this is the default value, pin it so it can't be bumped silently
        CIBW_ARCHS_WINDOWS: auto64
        CIBW_BUILD_VERBOSITY: 1
        CIBW_TEST_COMMAND: >
          python -m pip install -r {project}/test_requirements.txt
          && pytest --pyargs ewah_bool_utils --color=yes

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}
        path: ./dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build sdist
      run: pipx run build --sdist

    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  check_manifest:
    name: Check MANIFEST.in
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: install check-manifest
      run: |
        python -m pip install --upgrade pip
        python -m pip install check-manifest
    - name: Install build time dependencies
      shell: bash
      run: |
        python -m pip install "Cython>=3.0,<3.1"
        python -m pip install oldest-supported-numpy
        python -m pip install --upgrade wheel
        python -m pip install --upgrade setuptools
    - name: Build
      shell: bash
      run: |
        python -m pip install --no-build-isolation .
    - name: Init submodules
      uses: snickerbockers/submodules-init@v4
    - name: run check-manifest
      run: check-manifest -vvv

  deploy:
    name: Publish to PyPI
    needs: [build_wheels, build_sdist, check_manifest]
    runs-on: ubuntu-latest
    # upload to PyPI on every tag starting with 'v'
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
    - name: Download sdist
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: dist

    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: wheels-*
        merge-multiple: true

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
